Flask_blog/posts/forms.py
from wtforms import Form, StringField, validators, SubmitField


class CreatePostForm(Form):
    title = StringField("Title", validators=[
        validators.Length(min=10, message="Title must have at least 10 chars"),
        validators.DataRequired()], render_kw={"placeholder": "Enter a post title"})
    description = StringField("descrition",validators=[validators.Length(min="10",max="200",
                                message="Your post description must be between 10 and 250 characters")],
                              render_kw={"placeholder":"Enter a post description"})

    description = StringField("description", validators=[validators.Length(min=10,max=200,
                              message="Your post description must be between 10 and 250 characters"),
                              validators.DataRequired()], render_kw={"placeholder":"Enter a post description"})

    content = StringField("content", validators=[
        validators.Length(min=10, max=100000, message="Your post must contain between 10 and 100000 characters"),
        validators.DataRequired()], render_kw={"placeholder": "Enter a post"})

    submit = SubmitField("Create Post")

Flask_blog/posts/views.py
from flask import Blueprint, render_template, request, session, flash
from pymongo.errors import DuplicateKeyError

from Flask_blog.database.db import Mongo
from Flask_blog.posts import forms

posts = Blueprint("posts", __name__)


@posts.route("/create", methods=["GET", "POST"])
def create_post():
    database = Mongo(database="test", collection="posts", ServerSelectionTimeoutMS=5000)
    form = forms.CreatePostForm(request.form)
    if form.validate() and request.method == "POST":
        if not "username" in session:
            flash("You have to be logged in to add a post")
        else:
            post = {
                "title": form.title.data,
                "content": form.content.data,
                "description": form.description.data,
                "approved": False,
                "xss_protection_disabled": False,
                "author": session["username"]
            }
            try:
                database.insert(post)
                flash("Post was created")
                flash("Admin soon will check your post")
            except DuplicateKeyError:
                flash("This post title exist")
    return render_template("posts/create_post_form.html", form=form)


@posts.route("/<title>")
def get_post(title):
    database = Mongo(database="test", collection="posts", ServerSelectionTimeoutMS=5000)
    post = database.find(how_many="one", data_filter={"approved": True, "title": title},
                         projection={"content": 1, "author": 1, "title": 1, "xss_protection_disabled": 1})
    database = Mongo(database="test", collection="user", ServerSelectionTimeoutMS=5000)
    author = database.find(how_many="one", data_filter={"username": post["author"]}, projection={"trusted_user": 1})
    return render_template("posts/render_post.html", post=post, author=author)


@posts.route("/", methods=["GET", "POST"])
def list_post():
    database = Mongo(database="test", collection="posts", ServerSelectionTimeoutMS=5000)
    all_post = database.find(how_many="all", data_filter={"approved": True},
                             projection={"content": 1, "title": 1, "description": 1, "author": 1})
    return render_template("posts/show_posts.html", posts=all_post)

templates/posts/create_post_form.html
{% extends "site/base.html" %}
{% block content %}
<form action={{url_for("posts.create_post")}} method="post">
    <h1>Create a post</h1>
    {{ form.csrf_token }}
    {{form.title}}
    {{form.description()}}
    {{form.content()}}
    {{form.submit()}}
    {% for field in form.errors %}
    {% for error in form.errors[field] %}
    <div class="error">{{ error }}</div>
    {% endfor %}
    {% endfor %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <h1>{{message}}</h1>
        {% endfor %}
    {% endif %}
    {% endwith %}

</form>
{% endblock %}

templates/posts/render_post.html
{% extends "site/base.html" %}
{% block content %}
{% if post["xss_protection_disabled"] or author["trusted_user"] %}
{{post["content"]|safe}}
{% else %}
{{post["content"]}}
{% endif %}
{% endblock %}

templates/posts/show_posts.html
{% extends "site/base.html" %}
{% block css %}
<link
        rel="stylesheet"
        type="text/css"
        href="{{url_for('static',filename='css/style.css')}}"
/>
<link
        rel="stylesheet"
        type="text/css"
        href="{{url_for('static',filename='css/posts_style.css')}}"
/>


{% endblock %}
{% block content %}
{% for post in posts %}
    <div class="post">
        <div class="post_title"><a href='{{url_for("posts.get_post",title=post.title)}}'>{{post.title}} </a></div>
        {% if post.description %}
        <div class="post_description">{{post.description}} </div>
        {% else %}
        <div class="post_description">This post doesn't contain description</div>
        {% endif %}
        <div class="post_author">{{post.author}} </div>
    </div>
{% endfor %}
{% endblock %}