Flask_blog/posts/views.py
from flask import Blueprint, render_template, request, session, flash
from pymongo.errors import DuplicateKeyError

from Flask_blog.database.db import Mongo
from Flask_blog.posts import forms

posts = Blueprint("posts", __name__)


@posts.route("/create", methods=["GET", "POST"])
def create_post():
    database = Mongo(database="test", collection="posts", ServerSelectionTimeoutMS=5000)
    form = forms.CreatePostForm(request.form)
    if form.validate() and request.method == "POST":
        if not "username" in session:
            flash("You have to be logged in to add a post")
        else:
            post = {
                "title": form.title.data,
                "content": form.content.data,
                "description": form.description.data,
                "approved": False,
                "xss_protection_disabled": False,
                "author": session["username"]
            }
            try:
                database.insert(post)
                flash("Post was created")
                flash("Admin soon will check your post")
            except DuplicateKeyError:
                flash("This post title exist")
    return render_template("posts/create_post_form.html", form=form)


@posts.route("/<title>")
def get_post(title):
    database = Mongo(database="test", collection="posts", ServerSelectionTimeoutMS=5000)
    post = database.find(how_many="one", data_filter={"approved": True, "title": title},
                         projection={"content": 1, "author": 1, "title": 1, "xss_protection_disabled": 1})
    database = Mongo(database="test", collection="user", ServerSelectionTimeoutMS=5000)
    author = database.find(how_many="one", data_filter={"username": post["author"]}, projection={"trusted_user": 1})
    return render_template("posts/render_post.html", post=post, author=author)


@posts.route("/", methods=["GET", "POST"])
def list_post():
    database = Mongo(database="test", collection="posts", ServerSelectionTimeoutMS=5000)
    all_post = database.find(how_many="all", data_filter={"approved": True},
                             projection={"content": 1, "title": 1, "description": 1, "author": 1})
    return render_template("posts/show_posts.html", posts=all_post)

Flask_blog/user/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
import bcrypt
from werkzeug.utils import redirect

from Flask_blog.database.db import Mongo
from Flask_blog.user.forms import UserRegisterForm, UserLoginForm

user = Blueprint("user", __name__)

# database = Mongo(database="test", collection="user", ServerSelectionTimeoutMS=5000)


def create_hash(password: str):
    """
    Create password hash using bcrypt
    :param password:
    :return: password hash
    """
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt(rounds=14)).decode("utf-8")


@user.route("/register", methods=["GET", "POST"])
def signup():
    database = Mongo(database="test", collection="user", ServerSelectionTimeoutMS=5000)
    form = UserRegisterForm(request.form)
    if form.validate() and request.method == "POST":
        user = {
            "username": form.username.data,
            "password_hash": create_hash(form.password.data),
            "trusted_user": False,  # trusted_user posts will not be protected from xss attack
            "is_admin": False  # this have to be a bool don't use it like string "False" boolean value is true !!!
        }
        if database.find(data_filter={"username": form.username.data}) is None:
            database.insert(user)
            flash(message=f"Your account has been registered {form.username.data}")
            return redirect(url_for("user.signup_sucess", _method="GET"))
        else:
            flash(message="An account with this nickname already exists")
            return redirect(url_for("user.signup_sucess", _method="GET"))
    return render_template("auth/signup_form.html", form=form)


@user.route("/login", methods=["GET", "POST"])
def log_in():
    form = UserLoginForm(request.form)
    if form.validate() and request.method == "POST":
        if password_checker(form.username.data, form.password.data):
            session["username"] = form.username.data
            return redirect(url_for("main_page"))
    return render_template("auth/log_in_form.html", form=form)


@user.route("/sucess", methods=["GET"])
def signup_sucess():
    return render_template("auth/sucess.html")


@user.route("/logout")
def logout():
    session.pop("username")
    return redirect(url_for("main_page"))


def password_checker(username, password) -> bool:
    """
    Chceck if password is equal to user password
    :param username:check password for this user
    :param password:
    :return:
    True if password match, False otherwise
    """
    database = Mongo(database="test", collection="user", ServerSelectionTimeoutMS=5000)
    user_password_hash_db = database.find(data_filter={"username": username},
                                          projection={"password_hash": 1, "_id": 0})
    if isinstance(user_password_hash_db, dict):
        if bcrypt.checkpw(password.encode("utf-8"),
                          hashed_password=user_password_hash_db["password_hash"].encode("utf-8")):
            return True
    return False

templates/site/base.html
<html lang="en">
  <head>
      {% block css %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{{url_for('static',filename='css/style.css')}}"
    />
      {% endblock %}
    <link href="https://fonts.googleapis.com/css2?family=Recursive:wght@500&display=swap" rel="stylesheet">
    <meta charset="UTF-8" />
    {% block title %} {% endblock %}
  </head>

  <body>
   <nav class="navbar">
       <div class="blog_title">
       <a href="{{url_for("main_page")}}">NeroIT</a>
       </div>
       <div class="right_navbar">
           <ul>
           <li><a href="{{url_for("posts.list_post")}}">Posts</a></li>
           <li><a href=#>HOME</a></li>
           <li><a href=#>Faq</a></li>
            {% if session["username"] %}
            <div>
            <ul class="dropdown">
                <li><a href=#>{{session["username"]}}</a></li>
                <li class="dropdown-element-1"><a href="">Profile</a></li>
                <li class="dropdown-element-2"><a href="{{url_for("user.logout")}}">Sign out</a></li>
            </ul>
            </div>
            {% else %}
            <li><a href="{{url_for("user.log_in")}}">Login</a></li>
            <li><a href="{{url_for("user.signup")}}">Register</a></li>
            {% endif %}
           </ul>
       </div>
   </nav>
      <div class="middle">
          {% block content %} {% endblock %}
      </div>
    </div>
    <footer></footer>
  </body>
</html>